version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 533267226679.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t finaltest .
      - docker tag finaltest 533267226679.dkr.ecr.us-east-1.amazonaws.com/finaltest:ver1 
  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push 533267226679.dkr.ecr.us-east-1.amazonaws.com/finaltest:ver1
      - echo Image pushed to Amazon ECR
      # Output the ECR image URL
      - IMAGE_URL=$(aws ecr describe-images --repository-name finaltest --region $AWS_DEFAULT_REGION --query 'images[0].imageUri' --output text)
      - echo "ECR Image URL:$IMAGE_URL"
      # Save the image URL to a file
      - echo "$IMAGE_URL" > image_url.txt

artifacts:
  files:
    - image_url.txt
  discard-paths: yes
